# Form implementation generated from reading ui file 'ui/profileListWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfileListWindow(object):
    def setupUi(self, ProfileListWindow):
        ProfileListWindow.setObjectName("ProfileListWindow")
        ProfileListWindow.resize(378, 411)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ProfileListWindow.setWindowIcon(icon)
        ProfileListWindow.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    font-family: Rubik;\n"
"    background-color: #181818\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #cfcfcf;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"     border-collapse: separate;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #999;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QListWidget {\n"
"    border: 2px solid #cfcfcf;\n"
"    border-radius: 7px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ProfileListWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 361, 321))
        self.listWidget.setObjectName("listWidget")
        self.editProfileButton = QtWidgets.QPushButton(self.centralwidget)
        self.editProfileButton.setGeometry(QtCore.QRect(110, 360, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.editProfileButton.setFont(font)
        self.editProfileButton.setStyleSheet("border-radius: 7px;")
        self.editProfileButton.setObjectName("editProfileButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(340, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("color: #ffdbdc;")
        self.closeButton.setObjectName("closeButton")
        self.minimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.minimizeButton.setGeometry(QtCore.QRect(310, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setStyleSheet("color: #fffde0;")
        self.minimizeButton.setObjectName("minimizeButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 10, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.title.setStyleSheet("QLabel {\n"
"    color: #fefefe;\n"
"}")
        self.title.setObjectName("title")
        ProfileListWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ProfileListWindow)
        self.statusbar.setObjectName("statusbar")
        ProfileListWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(ProfileListWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(ProfileListWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(ProfileListWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfileListWindow)

    def retranslateUi(self, ProfileListWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfileListWindow.setWindowTitle(_translate("ProfileListWindow", "Список профилей"))
        self.editProfileButton.setText(_translate("ProfileListWindow", "Редактировать"))
        self.closeButton.setText(_translate("ProfileListWindow", "X"))
        self.minimizeButton.setText(_translate("ProfileListWindow", "_"))
        self.title.setText(_translate("ProfileListWindow", "<html><head/><body><p>Редактирование профилей</p></body></html>"))
        self.action.setText(_translate("ProfileListWindow", "Сбросить базу данных"))
        self.action_2.setText(_translate("ProfileListWindow", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfileListWindow = QtWidgets.QMainWindow()
    ui = Ui_ProfileListWindow()
    ui.setupUi(ProfileListWindow)
    ProfileListWindow.show()
    sys.exit(app.exec())
