# Form implementation generated from reading ui file 'src/ui/mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(605, 427)
        MainWindow.setStyleSheet("QWidget {\n"
"   background-color: #13171c;\n"
"   color: #f5f5f5;\n"
"   font-family:  Rubik;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #cfcfcf;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #1d2024;\n"
"    border: none;\n"
"     border-collapse: separate;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #222a33;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #1d2329;\n"
"}\n"
"\n"
"QListWidget {\n"
"    border: 2px solid #cfcfcf;\n"
"    border-radius: 7px;\n"
"}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setStyleSheet("")
        self.mainWidget.setObjectName("mainWidget")
        self.closeButton = QtWidgets.QPushButton(self.mainWidget)
        self.closeButton.setGeometry(QtCore.QRect(560, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("")
        self.closeButton.setObjectName("closeButton")
        self.minimizeButton = QtWidgets.QPushButton(self.mainWidget)
        self.minimizeButton.setGeometry(QtCore.QRect(520, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setStyleSheet("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.navigationWidget = QtWidgets.QWidget(self.mainWidget)
        self.navigationWidget.setGeometry(QtCore.QRect(0, 0, 61, 431))
        self.navigationWidget.setStyleSheet("QWidget {\n"
"   background-color: #586675;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"   background-color: #505d6b;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"   background-color: #44515e;\n"
"}")
        self.navigationWidget.setObjectName("navigationWidget")
        self.profilesButton = QtWidgets.QPushButton(self.navigationWidget)
        self.profilesButton.setGeometry(QtCore.QRect(10, 50, 41, 41))
        self.profilesButton.setObjectName("profilesButton")
        self.settingsButton = QtWidgets.QPushButton(self.navigationWidget)
        self.settingsButton.setGeometry(QtCore.QRect(10, 100, 41, 41))
        self.settingsButton.setObjectName("settingsButton")
        self.title = QtWidgets.QLabel(self.navigationWidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.title.setStyleSheet("color: #ffffff;")
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.adButton = QtWidgets.QPushButton(self.navigationWidget)
        self.adButton.setGeometry(QtCore.QRect(0, 400, 61, 21))
        self.adButton.setStyleSheet("")
        self.adButton.setObjectName("adButton")
        self.settingsWidget = QtWidgets.QWidget(self.mainWidget)
        self.settingsWidget.setEnabled(True)
        self.settingsWidget.setGeometry(QtCore.QRect(60, 0, 541, 431))
        self.settingsWidget.setStyleSheet("")
        self.settingsWidget.setObjectName("settingsWidget")
        self.settingsTitle = QtWidgets.QLabel(self.settingsWidget)
        self.settingsTitle.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        self.settingsTitle.setFont(font)
        self.settingsTitle.setObjectName("settingsTitle")
        self.profilesWidget = QtWidgets.QWidget(self.mainWidget)
        self.profilesWidget.setEnabled(True)
        self.profilesWidget.setGeometry(QtCore.QRect(60, 0, 541, 431))
        self.profilesWidget.setStyleSheet("")
        self.profilesWidget.setObjectName("profilesWidget")
        self.newProfileButton = QtWidgets.QPushButton(self.profilesWidget)
        self.newProfileButton.setGeometry(QtCore.QRect(470, 80, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.newProfileButton.setFont(font)
        self.newProfileButton.setStyleSheet("")
        self.newProfileButton.setObjectName("newProfileButton")
        self.editProfileButton = QtWidgets.QPushButton(self.profilesWidget)
        self.editProfileButton.setGeometry(QtCore.QRect(470, 150, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.editProfileButton.setFont(font)
        self.editProfileButton.setStyleSheet("")
        self.editProfileButton.setObjectName("editProfileButton")
        self.deleteProfileButton = QtWidgets.QPushButton(self.profilesWidget)
        self.deleteProfileButton.setGeometry(QtCore.QRect(470, 220, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.deleteProfileButton.setFont(font)
        self.deleteProfileButton.setStyleSheet("")
        self.deleteProfileButton.setObjectName("deleteProfileButton")
        self.profilesTitle = QtWidgets.QLabel(self.profilesWidget)
        self.profilesTitle.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        self.profilesTitle.setFont(font)
        self.profilesTitle.setObjectName("profilesTitle")
        self.listWidget = QtWidgets.QListWidget(self.profilesWidget)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(20, 80, 431, 321))
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.profilesWidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listWidget.raise_()
        self.newProfileButton.raise_()
        self.editProfileButton.raise_()
        self.deleteProfileButton.raise_()
        self.profilesTitle.raise_()
        self.label.raise_()
        self.settingsWidget.raise_()
        self.navigationWidget.raise_()
        self.profilesWidget.raise_()
        self.minimizeButton.raise_()
        self.closeButton.raise_()
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное меню"))
        self.closeButton.setText(_translate("MainWindow", "X"))
        self.minimizeButton.setText(_translate("MainWindow", "_"))
        self.profilesButton.setText(_translate("MainWindow", "P"))
        self.settingsButton.setText(_translate("MainWindow", "S"))
        self.title.setText(_translate("MainWindow", "AB"))
        self.adButton.setText(_translate("MainWindow", "GitHub"))
        self.settingsTitle.setText(_translate("MainWindow", "Настройки"))
        self.newProfileButton.setText(_translate("MainWindow", "N"))
        self.editProfileButton.setText(_translate("MainWindow", "E"))
        self.deleteProfileButton.setText(_translate("MainWindow", "D"))
        self.profilesTitle.setText(_translate("MainWindow", "Профили"))
        self.label.setText(_translate("MainWindow", "Ваши профили:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
