# Form implementation generated from reading ui file 'src/ui/profileListWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfileListWindow(object):
    def setupUi(self, ProfileListWindow):
        ProfileListWindow.setObjectName("ProfileListWindow")
        ProfileListWindow.resize(378, 429)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ProfileListWindow.setWindowIcon(icon)
        ProfileListWindow.setStyleSheet("QWidget {\n"
"   background-color: #13171c;\n"
"   color: #f5f5f5;\n"
"   font-family:  Rubik;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #cfcfcf;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #1d2024;\n"
"    border: none;\n"
"     border-collapse: separate;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #222a33;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #1d2329;\n"
"}\n"
"\n"
"QListWidget {\n"
"    border: 2px solid #cfcfcf;\n"
"    border-radius: 7px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ProfileListWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 361, 321))
        self.listWidget.setStyleSheet("QWidget {\n"
"   background-color: #586675;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"   background-color: #505d6b;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"   background-color: #44515e;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.editProfileButton = QtWidgets.QPushButton(self.centralwidget)
        self.editProfileButton.setGeometry(QtCore.QRect(110, 380, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.editProfileButton.setFont(font)
        self.editProfileButton.setStyleSheet("")
        self.editProfileButton.setObjectName("editProfileButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.title.setStyleSheet("QLabel {\n"
"    color: rgb(220, 220, 220)\n"
"}")
        self.title.setObjectName("title")
        self.minimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.minimizeButton.setGeometry(QtCore.QRect(300, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setStyleSheet("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(340, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(11)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("")
        self.closeButton.setObjectName("closeButton")
        ProfileListWindow.setCentralWidget(self.centralwidget)
        self.action = QtGui.QAction(ProfileListWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(ProfileListWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(ProfileListWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfileListWindow)

    def retranslateUi(self, ProfileListWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfileListWindow.setWindowTitle(_translate("ProfileListWindow", "Список профилей"))
        self.editProfileButton.setText(_translate("ProfileListWindow", "Редактировать"))
        self.title.setText(_translate("ProfileListWindow", "<html><head/><body><p>Редактирование профилей</p></body></html>"))
        self.minimizeButton.setText(_translate("ProfileListWindow", "_"))
        self.closeButton.setText(_translate("ProfileListWindow", "X"))
        self.action.setText(_translate("ProfileListWindow", "Сбросить базу данных"))
        self.action_2.setText(_translate("ProfileListWindow", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfileListWindow = QtWidgets.QMainWindow()
    ui = Ui_ProfileListWindow()
    ui.setupUi(ProfileListWindow)
    ProfileListWindow.show()
    sys.exit(app.exec())
